### ISSUE TITLE
Refactor Flask to use Blueprints

### ISSUE THREAD

**Issue by jpappel** [cs298-398f23/file-fortress#19]
The current implementation of endpoints uses some import magic for modularity. I suggest we use the builtin Flask feature of [blueprints](https://flask.palletsprojects.com/en/3.0.x/blueprints/) as an alternative. This change would likely allow us to remove the various `__init__.py` that exist for proper sourcing.

**Comment by drekdrek** [comment]
can you generate a secret key on image build?
