### ISSUE TITLE
Plumbing

### ISSUE THREAD

**Issue by jpappel** [cs298-398f23/file-fortress#5]
Tasks for "plumbing" that need to be implemented for Monday, November 20 - Team meetings with demo.

* [x] publicly accessible website
* [ ] flask serving content from s3
* [ ] flask reading and writing from database
* [x] database schema

🏰 📁

**Comment by drekdrek** [comment]
For Monday:
* [ ] code running in an EC2 Instance
    * [ ] Flask Server
    * [ ] Database
    * [ ] Deploy Script
* [ ] S3 Bucket

**Comment by jpappel** [comment]
S3 seems out of scope for the plumbing
